#include "addresses.hpp"

#include <stdint.h>

const int EEPROM_CYCLIC_MODE_SETTINGS_ADDRESS  = 0;
const int EEPROM_CUSTOM_MODE_SETTINGS_ADDRESS = EEPROM_CYCLIC_MODE_SETTINGS_ADDRESS + sizeof(uint32_t) * 4;
const int NUM_CUSTOM_MODE_SETTINGS = 24;
const int EEPROM_DEFAULT_IRRIGATION_MODE_SETTING_ADDRESS = EEPROM_CUSTOM_MODE_SETTINGS_ADDRESS + sizeof(uint32_t) * 2 * NUM_CUSTOM_MODE_SETTINGS;
const int EEPROM_PUMP_MOTOR_ENABLED_ADDRESS = EEPROM_DEFAULT_IRRIGATION_MODE_SETTING_ADDRESS + sizeof(uint8_t);
const int EEPROM_PREVENT_WATER_HAMMER_SETTING_ADDRESS = EEPROM_PUMP_MOTOR_ENABLED_ADDRESS + sizeof(bool);

// EEPROM_PREVENT_WATER_HAMMER_SETTING_ADDRESS + sizeof(uint16_t) * 2
